# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Auth Controller

# Model Form Field configuration
form: ~/app/models/authcontroller/fields.yaml

# Model Class name
modelClass: App\Models\AuthController

# Default redirect location
defaultRedirect: app/authcontroller

# Create page
create:
    title: backend::lang.form.create_title
    redirect: app/authcontroller/update/:id
    redirectClose: app/authcontroller

# Update page
update:
    title: backend::lang.form.update_title
    redirect: app/authcontroller
    redirectClose: app/authcontroller

# Preview page
preview:
    title: backend::lang.form.preview_title
